// options are composed of 2 properties: values and labels
export const options = [
    {value: 'false', label: 'None'},
    {value: 'AUD', label: 'Australian Dollar'},
    {value: 'BGN', label: 'Bulgarian Lev'},
    {value: 'BRL', label: 'Brazilian Real'},
    {value: 'CAD', label: 'Canadian Dollar'},
    {value: 'CNY', label: 'Chinese Yuan'},
    {value: 'HRK', label: 'Croatian Kuna'},
    {value: 'CZK', label: 'Czech Koruna'},
    {value: 'DKK', label: 'Danish Krone'},
    {value: 'EUR', label: 'Euro'},
    {value: 'GBP', label: 'Great Britain Pound Sterling'},
    {value: 'HKD', label: 'Hong Kong Dollar'},
    {value: 'HUF', label: 'Hungarian Forint'},
    {value: 'INR', label: 'Indian Rupee'},
    {value: 'IDR', label: 'Indonesian Rupiah'},
    {value: 'ILS', label: 'Israeli New Shekel'},
    {value: 'JPY', label: 'Japanese Yen'},
    {value: 'MYR', label: 'Malaysian Ringgit'},
    {value: 'MXN', label: 'Mexican Peso'},
    {value: 'NZD', label: 'New Zealand Dollar'},
    {value: 'NOK', label: 'Norwegian Krone'},
    {value: 'PSP', label: 'Philippine Peso'},
    {value: 'PLN', label: 'Poland Zloty'},
    {value: 'RON', label: 'Romanian Leu'},
    {value: 'RUB', label: 'Russian Ruble'},
    {value: 'SGD', label: 'Singapore Dollar'},
    {value: 'ZAR', label: 'South African Rand'},
    {value: 'KRW', label: 'South Korean Won'},
    {value: 'SEK', label: 'Swedish Krona'},
    {value: 'CHF', label: 'Swiss Franc'},
    {value: 'THB', label: 'Thai Baht'},
    {value: 'TRY', label: 'Turkish lira'},
    {value: 'USD', label: 'United States Dollar'},
]